//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace SpeechCustomUi.NLP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://NLPServer/", ConfigurationName="NLP.NLPWebService")]
    public interface NLPWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NLPServer/NLPWebService/helloRequest", ReplyAction="http://NLPServer/NLPWebService/helloResponse")]
        System.Threading.Tasks.Task<SpeechCustomUi.NLP.helloResponse> helloAsync(SpeechCustomUi.NLP.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NLPServer/NLPWebService/DoNLPRequest", ReplyAction="http://NLPServer/NLPWebService/DoNLPResponse")]
        System.Threading.Tasks.Task<SpeechCustomUi.NLP.DoNLPResponse> DoNLPAsync(SpeechCustomUi.NLP.DoNLPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://NLPServer/", Order=0)]
        public SpeechCustomUi.NLP.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(SpeechCustomUi.NLP.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://NLPServer/", Order=0)]
        public SpeechCustomUi.NLP.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(SpeechCustomUi.NLP.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoNLPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoNLP", Namespace="http://NLPServer/", Order=0)]
        public SpeechCustomUi.NLP.DoNLPRequestBody Body;
        
        public DoNLPRequest() {
        }
        
        public DoNLPRequest(SpeechCustomUi.NLP.DoNLPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DoNLPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string words;
        
        public DoNLPRequestBody() {
        }
        
        public DoNLPRequestBody(string words) {
            this.words = words;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoNLPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoNLPResponse", Namespace="http://NLPServer/", Order=0)]
        public SpeechCustomUi.NLP.DoNLPResponseBody Body;
        
        public DoNLPResponse() {
        }
        
        public DoNLPResponse(SpeechCustomUi.NLP.DoNLPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DoNLPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public DoNLPResponseBody() {
        }
        
        public DoNLPResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NLPWebServiceChannel : SpeechCustomUi.NLP.NLPWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NLPWebServiceClient : System.ServiceModel.ClientBase<SpeechCustomUi.NLP.NLPWebService>, SpeechCustomUi.NLP.NLPWebService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NLPWebServiceClient() : 
                base(NLPWebServiceClient.GetDefaultBinding(), NLPWebServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.NLPWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NLPWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NLPWebServiceClient.GetBindingForEndpoint(endpointConfiguration), NLPWebServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NLPWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NLPWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NLPWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NLPWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NLPWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpeechCustomUi.NLP.helloResponse> SpeechCustomUi.NLP.NLPWebService.helloAsync(SpeechCustomUi.NLP.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpeechCustomUi.NLP.helloResponse> helloAsync(string name) {
            SpeechCustomUi.NLP.helloRequest inValue = new SpeechCustomUi.NLP.helloRequest();
            inValue.Body = new SpeechCustomUi.NLP.helloRequestBody();
            inValue.Body.name = name;
            return ((SpeechCustomUi.NLP.NLPWebService)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpeechCustomUi.NLP.DoNLPResponse> SpeechCustomUi.NLP.NLPWebService.DoNLPAsync(SpeechCustomUi.NLP.DoNLPRequest request) {
            return base.Channel.DoNLPAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpeechCustomUi.NLP.DoNLPResponse> DoNLPAsync(string words) {
            SpeechCustomUi.NLP.DoNLPRequest inValue = new SpeechCustomUi.NLP.DoNLPRequest();
            inValue.Body = new SpeechCustomUi.NLP.DoNLPRequestBody();
            inValue.Body.words = words;
            return ((SpeechCustomUi.NLP.NLPWebService)(this)).DoNLPAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NLPWebServicePort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NLPWebServicePort)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/NLPWebService2/NLPWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return NLPWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.NLPWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return NLPWebServiceClient.GetEndpointAddress(EndpointConfiguration.NLPWebServicePort);
        }
        
        public enum EndpointConfiguration {
            
            NLPWebServicePort,
        }
    }
}
